#! /bin/sh

xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &
#$HOME/.fehbg

# inicio con el sistema
#bash ~/.config/polybar/launch.sh --shades
#~/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpg &
picom &
dunst &

# Monitores
bspc monitor -d I II III IV V VI VII VIII IX X

#### BSPWM colores
bspc config normal_border_color		      "#e5e9f0"
bspc config active_border_color	       	      "#e5e9f0"
bspc config focused_border_color	      "#2492e0"
bspc config presel_feedback_color	      "#b48ead"
bspc config urgent_border_color 	      "#ebcb8b"

#### BSPWM configuration
bspc config border_width        	  2
bspc config window_gap         		  12
bspc config border_radius                 8
bspc config top_padding                   35
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config split_ratio          	  0.52
bspc config borderless_monocle   	  true
bspc config gapless_monocle      	  true

# Reglas de como abren las apps
bspc rule -a Pavucontrol state=tiled rectangle=600x400+0+0 center=on desktop='^4'
bspc rule -a Code state=tiled rectangle=800x500+0+0 center=on desktop='^6'
bspc rule -a TelegramDesktop state=tiled rectangle=800x500+0+0 center=on desktop='^5'
bspc rule -a Org.gnome.Nautilus state=tiled rectangle=800x500+0+0 center=on desktop='^3'
bspc rule -a Lxappearance state=tiled rectangle=800x500+0+0 center=on desktop='^4'
bspc rule -a xfce4-terminal state=tiled rectangle=800x500+0+0 center=on desktop='^1'
bspc rule -a qtws state=tiled rectangle=800x500+0+0 center=on desktop='^6'
bspc rule -a Google-chrome state=tiled rectangle=800x500+0+0 center=on desktop='^2'
bspc rule -a firefox state=tiled rectangle=800x500+0+0 center=on desktop='^2'
bspc rule -a Nitrogen state=tiled rectangle=800x500+0+0 center=on desktop='^4'
bspc rule -a obs state=tiled rectangle=800x500+0+0 center=on desktop='^5'
bspc rule -a Gedit state=tiled rectangle=800x500+0+0 center=on desktop='^3'
